### PR TITLE
Changes in readme.md

### PR DESCRIPTION
**Pull request by manasb15**
ISSUE #46 

#### Describe the changes you've made:
I corrected the website's name in the About section, corrected and changed a few sentences in the documentation to make it more error-free.
Added a few ':' wherever found necessary.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

Changes made under DevIncept Open Source Program.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@manasb15 remove":" from every section project admin, license, etc.

Add we in this line: not being able to find what 'we' are looking for,

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Okay makes sense got it.

**Comment by QAZIMAAZARSHAD** [comment]
@satyampgt4 we will add labels in PR after they are successfully merged so PR's which were merged by mistake or follow-up PR's will not get counted.
And don't add labels in PR I will do that part because I have to keep a count.

**Comment by satyampgt4** [comment]
> @satyampgt4 we will add labels in PR after they are successfully merged so PR's which were merged by mistake or follow-up PR's will not get counted.
> And don't add labels in PR I will do that part because I have to keep a count.

Okay 👍🏻

**Comment by QAZIMAAZARSHAD** [comment]
@manasb15  Fill this form https://docs.google.com/forms/d/e/1FAIpQLSeWRqZljejl0NnH8v4PqkjfTsWoQAbx_n0xR25PHaNiZnbnAw/viewform

Mention only those PR links which have DCP label.

**Pull request merged**
