### PR TITLE
Design a new creative about us page

### LINKED ISSUE #52: Design a new creative about us page

### PR DESCRIPTION
**Pull request by ChristineLeong**
#### Describe the changes you've made
I have redesign the whole about us page. Seperated the description into different part and make more interaction stuff like hover, some animation like slide in description when scroll down, description fade in when loaded, added some script to show the progress bar of scrolling. Modify the style of scroll top button.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
image
image
image

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x ] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x ] The title of my pull request is a short description of the requested changes.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@ChristineLeong make the footer and header the same as the home page.

**Comment by ChristineLeong** [comment]
> @ChristineLeong make the footer and header the same as the home page.

Hi i have changed the footer and header same as the main page

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

**Comment by ChristineLeong** [comment]
> Share the website link so I can review your changes.



> Share the website link so I can review your changes.

https://christineleong.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
Looks great @ChristineLeong.

There are few spelling mistakes in the content like "delibery", "noew" etc. Go through the content and correct the grammatical and typo errors.

**Comment by ChristineLeong** [comment]
> Looks great @ChristineLeong.
> 
> There are few spelling mistakes in the content like "delibery", "noew" etc. Go through the content and correct the grammatical and typo errors.

Corrected the typo and grammarical error by using grammar checking tools

**Comment by QAZIMAAZARSHAD** [comment]
> > Looks great @ChristineLeong.
> > There are few spelling mistakes in the content like "delibery", "noew" etc. Go through the content and correct the grammatical and typo errors.
> 
> Corrected the typo and grammarical error by using grammar checking tools

As you wish, there are not that much grammatical and typo errors if you see any just correct them.

**Comment by ChristineLeong** [comment]
> > > Looks great @ChristineLeong.
> > > There are few spelling mistakes in the content like "delibery", "noew" etc. Go through the content and correct the grammatical and typo errors.
> > 
> > 
> > Corrected the typo and grammarical error by using grammar checking tools
> 
> As you wish, there are not that much grammatical and typo errors if you see any just correct them.

I have corrected them by using grammatical checking tools just now, you can check it.

**Comment by QAZIMAAZARSHAD** [comment]
@ChristineLeong fill the google form.

Link in the slack channel.

**Comment by ChristineLeong** [comment]
> @ChristineLeong fill the google form.
> 
> Link in the slack channel.

I'm not engage in the dcp.

**Comment by QAZIMAAZARSHAD** [comment]
Fine

**Pull request merged**
