### PR TITLE
Removed About Us Page from Home Page

### PR DESCRIPTION
**Pull request by techabhi08**
#### Describe the changes you've made
I have removed the about us section from home page and a new page is been made for the same. The new file is named about.html. This about page is linked with the home page so the name given in home page i.e. "About us" will take user to this separate about us page. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshot (475)

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(LetsGrowMore SummerOfCode)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@techabhi08 looks like you have removed the footer from the index page.

**Comment by QAZIMAAZARSHAD** [comment]
Also about us page is similar.

I was expecting a better and new design of the page.
Remember more the efforts higher the points you will gain.

**Comment by techabhi08** [comment]
Sir do you need the footer in the home page itself? So should I shift just the content of About us page and redesign it.

**Comment by QAZIMAAZARSHAD** [comment]
> Sir do you need the footer in the home page itself? So should I shift just the content of About us page and redesign it.

Yes, the footer and header should be on every page.

**Comment by techabhi08** [comment]
Okay sir I have solved that issue. I will try to redesign and give a better look to about us page now.

**Comment by techabhi08** [comment]
Sir while changing I found another issue that it is not possible to go to the deals page from contact page. The link is missing there so should I open a new issue for that or fix that in this one only?

**Comment by QAZIMAAZARSHAD** [comment]
> Sir while changing I found another issue that it is not possible to go to the deals page from contact page. The link is missing there so should I open a new issue for that or fix that in this one only?

If you have more issues solve them separately it will get you more points.

**Comment by techabhi08** [comment]
okay sir.

**Comment by techabhi08** [comment]
Screenshot (477)

Sir I have added header and footer both. Also formatted the paragraph. Added some margin to align the text. So should I open a new PR with this or any more changes required?

**Comment by techabhi08** [comment]
Sir I can add more customization like changing the colour theme of this page but then it will look different from the other pages and will not match there style.

**Comment by QAZIMAAZARSHAD** [comment]
Fine

**Pull request closed without merging**
