### PR TITLE
Integrate Payment Gateway in our website

### LINKED ISSUE #25: Improve the payments page

### PR DESCRIPTION
**Pull request by Rishita11**
#### Fixes #25 
 
I am creating this Pull Request to solve issue 25 i.e to integrate Payment Gateway in our website. 

Description:
I have added a page when the user clicks on the "Buy Now" button in the cart section. Then he will be navigated to the credit card payment options. Some details will be taken such as card number, name of the card holder, expiry date, and CVV. Then on clicking the "Pay Now" button, payment will be done. But since it is a dummy website, therefore, no actions will be taken. So, that it is completely safe.

The link to show the demo on our website - "Apni-Dukaan" is: https://rishita11.github.io/pay.github.io/

There is no unusual behavior in my code. (NA)

Screenshots:
Screenshot (264)

Checklist

- [ x] I have mentioned related issue numbers in the PR description.
- [ x] I have added screenshots and related demo links of my changes..
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ x] Open Source Program names- DevIncept

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Rishita11 fetch upstream your repo is 65 commits behind.

**Comment by QAZIMAAZARSHAD** [comment]
The pay button is not responding anything.

It should display a pop-up as payment received. Track your order.
Or should redirect to another page.

**Comment by QAZIMAAZARSHAD** [comment]
Add something in the background as well.

Check responsiveness in mobile view.

**Comment by Rishita11** [comment]
Okay, I will make the necessary changes.

**Comment by QAZIMAAZARSHAD** [comment]
@Rishita11 the website has been updated.

Check. https://qazimaazarshad.github.io/Apni-Dukaan/payment.html

You can improve it. If you still want to work on this issue.

**Pull request closed without merging**
