### PR TITLE
Modify footer to be more attractive

### LINKED ISSUE #35: Making the footer attractive and linking its items

### PR DESCRIPTION
**Pull request by Sia0**
#### Describe the changes you've made
I modify the footer to be more attractive in index page.
-Hover over the link in footer, bold the link.
-Hover over the social media button, bold the link + add respective color to icon.
-Modify style of footer arrangement
-Checked and update the responsive footer

#### Additional context (OPTIONAL)
image

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by Sia0** [comment]
@QAZIMAAZARSHAD sir is this ok?

**Comment by Sia0** [comment]
https://sia0.github.io/Apni-Dukaan/
This is the link to view the changes.

**Comment by QAZIMAAZARSHAD** [comment]
Add connect with us section in the same row with other sections.

And update the footer in every single page.

**Comment by Sia0** [comment]
you mean something like this?
image

**Comment by QAZIMAAZARSHAD** [comment]
Yes, but the margin on right is large.

Reduce it.

**Comment by Sia0** [comment]
Modified Sir. You may check again

**Pull request merged**
