### PR TITLE
redesigned offers page #231

### LINKED ISSUE #231: Redesign Offers Page
Make improvements or completely redesign the page.

https://qazimaazarshad.github.io/Apni-Dukaan/offers.html

Make sure the new design must be similar to the entire theme of the website.

### PR DESCRIPTION
**Pull request by navya-Singla-1-3-0-9**
#### Describe the changes you've made
Redesigned the offer page
#### Snapshots:
image

image

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@navya-Singla-1-3-0-9 please share a live link to the website so I can review your changes.

**Comment by navya-Singla-1-3-0-9** [comment]
> @navya-Singla-1-3-0-9 please share a live link to the website so I can review your changes.

Please review the changes at https://navya-singla-1-3-0-9.github.io/Apni-Dukaan/offers.html

**Comment by QAZIMAAZARSHAD** [comment]
@navya-Singla-1-3-0-9 the topmost image is not showing.
And update the footer, it has error, Compare the footer with the contactus page.
And the card for dairy is smaller than the rest. Fix it.

**Comment by navya-Singla-1-3-0-9** [comment]
Image will be visible once it is available in the master branch, as relative path is being used. I have made rest of the fixes.

**Comment by QAZIMAAZARSHAD** [comment]
image

The size of the Dairy card is still small compared to others.

**Comment by QAZIMAAZARSHAD** [comment]
https://navya-singla-1-3-0-9.github.io/Apni-Dukaan/offers.html

your changes are not showing.

**Comment by navya-Singla-1-3-0-9** [comment]
Corrected card size. Here is a video 
https://drive.google.com/file/d/10_HW83nvlYbIUT71Ozo3yAaMWn-3LNq3/view?usp=sharing.
I am getting deployment failures which is stated to be because of in progress deployment. Will try to get it deployed:(

**Comment by QAZIMAAZARSHAD** [comment]
@navya-Singla-1-3-0-9 https://qazimaazarshad.github.io/Apni-Dukaan/offers.html 

add image in this repo and update location.

**Pull request merged**
