### PR TITLE
Modify FAQ page (Fix #113)

### LINKED ISSUE #113: Redesign the Faq page.
## Is your feature request related to a problem? Please describe.
The Faq stick the wall

## Describe the solution you'd like
Create a container for faq to avoid the problem

## Additional context
Add any other context about the feature request here.
I would like to try to modify the faq page. Can you assign this issue to me?

### PR DESCRIPTION
**Pull request by LeeSinYung**
#### Describe the changes you've made
I change the design of FAQ page. Example, I remove the accordian and replace by details,summary method which look more tidy. I added documentation on my modify part.

#### Deploy your changes to github page or netlify and mention deployment link:
Screenshot of modify FAQ
image

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
N/A

#### Checklist

- [/] I have mentioned related issue number in PR description.
- [/] I have added screenshots and related demo links of my changes..
- [/] The title of my pull request is a short description of the requested changes.
- [/] My code follows the code style of this project.
- [/] My change requires a change to the documentation.
- [/] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by LeeSinYung** [comment]
Reupload the Screen shot 
image

**Comment by QAZIMAAZARSHAD** [comment]
@LeeSinYung always mention the issue number like this #113 in the PR description.

**Comment by QAZIMAAZARSHAD** [comment]
@LeeSinYung host your website on any platform then share the link so I can review your changes.

**Comment by LeeSinYung** [comment]
@QAZIMAAZARSHAD  https://leesinyung.github.io/Apni-Dukaan/

**Pull request merged**
