### PR TITLE
landingPage

### LINKED ISSUE #23: Design a landing page
It should redirect to the login page

### PR DESCRIPTION
**Pull request by Shivani13121007**

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

**Comment by Shivani13121007** [comment]
Link
Which type of link?
As it's in my localhost 
How can u access that?

**Comment by QAZIMAAZARSHAD** [comment]
Deploy your website somewhere like netify, repl.it, or GitHub pages.

Then share.

**Comment by Shivani13121007** [comment]
Here is the link
https://elated-wozniak-048845.netlify.app/

**Comment by QAZIMAAZARSHAD** [comment]
Don't forget to fill the google form.

Link in slack channel.

**Pull request merged**
