### PR TITLE
Furniture Page

### LINKED ISSUE #11: Create a  furniture page

### PR DESCRIPTION
**Pull request by tjanhvi**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by tjanhvi** [comment]
https://tjanhvi.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
image
Images not displaying

Link furniture page here as well
image

**Comment by tjanhvi** [comment]
but from my side it's visible
Screenshot (199)
Screenshot (200)
Screenshot (201)
Screenshot (202)
Screenshot (203)

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi check the link you shared.

**Comment by QAZIMAAZARSHAD** [comment]
Something's must be wrong. And link furniture page in the home page.

**Comment by tjanhvi** [comment]
https://tjanhvi.github.io/Apni-Dukaan/
Now check this link......

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi your footer is not updated. Compare with other pages.

And fetch upstream your repository is few commits behind.

Also, link the furniture page to the home page furniture button.

**Comment by tjanhvi** [comment]
> @tjanhvi your footer is not updated. Compare with other pages.
> 
> And fetch upstream your repository is few commits behind.
> 
> Also, link the furniture page to the home page furniture button.

okay

**Pull request closed without merging**
