### PR TITLE
Added Signup Page

### LINKED ISSUE #15: Redesign the sign-up page

### PR DESCRIPTION
**Pull request by Swastik1710**
#### Describe the changes you've made
Added Signup page with required validations.

#### Deploy your changes to github page or netlify and mention deployment link:
https://swastik1710.github.io/Apni-Dukaan/

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) - DCP 2021

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Nice work @Swastik1710.

But there are few issues.

In Mobile View buttons inside movie cards are not displaying.
image
I suggest adjusting the size of all cards like anime and Tv pages these two are fine or adjusting the content inside the cards.

You forgot to check responsiveness on the premium page.
image

You forgot to check responsiveness on the quiz page.
image

The form on the sign-up page is slightly more towards the left.
image

**Comment by Swastik1710** [comment]
I'm unable to make the premium page responsive as it has some other bugs too.
You can create a different issue for the premium page. I'm unable to do it. 
Rest all errors, I'll take care of.

**Comment by Swastik1710** [comment]
BTW we're discussing about Movie Streaming Website but this is the Apni Dukaan repository

**Comment by QAZIMAAZARSHAD** [comment]
> BTW we're discussing about Movie Streaming Website but this is the Apni Dukaan repository

Ooops really sorry.

Sometimes it becomes very confusing.

**Comment by QAZIMAAZARSHAD** [comment]
> I'm unable to make the premium page responsive as it has some other bugs too.
> You can create a different issue for the premium page. I'm unable to do it.
> Rest all errors, I'll take care of.

Sure leave the premium page.

**Comment by Swastik1710** [comment]
> > BTW we're discussing about Movie Streaming Website but this is the Apni Dukaan repository
> 
> Ooops really sorry.
> 
> Sometimes it becomes very confusing.

Yeah i know.
It happens, no worries.

**Comment by QAZIMAAZARSHAD** [comment]
@Swastik1710 the sign-up page is not redirecting to the home page after signing up.

Also, email is getting accepted without ".com".

**Comment by Swastik1710** [comment]
Done!

**Comment by QAZIMAAZARSHAD** [comment]
Redirect to the home page, not index page.

**Comment by QAZIMAAZARSHAD** [comment]
Fetch upstream.

**Comment by Swastik1710** [comment]
> 
> 
> Fetch upstream.

Done !
Please check now.

**Comment by Swastik1710** [comment]
Please check it now. 
I think it should be ok now.

**Pull request merged**
