### PR TITLE
Preloader is added successfully with a white background

### LINKED ISSUE #19: Add a creative pre-loader in website
Use the logo of the website and apply some creative effects

### PR DESCRIPTION
**Pull request by Kjp04**
#### Describe the changes you've made
I added a preloader in gif format. The files changes are index.html and style.css

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?
Run the index.html file to note the changes

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Kjp04 close the PR which you don't want to be evaluated.

Mention issue number like this #19.

And always share a deployment link to test your changes.

**Comment by Kjp04** [comment]
https://kjp04.github.io/Apni-Dukaan/
This is the link you can check out.
Sorry for the inconvenience.

**Comment by QAZIMAAZARSHAD** [comment]
> https://kjp04.github.io/Apni-Dukaan/
> This is the link you can check out.
> Sorry for the inconvenience.

This PR is closed.
You should have sent it in other PR.

**Comment by Kjp04** [comment]
https://kjp04.github.io/Apni-Dukaan/
This is the link you can check out.
Sorry for the inconvenience.

**Pull request closed without merging**
