### PR TITLE
#49

### PR DESCRIPTION
**Pull request by ushmita4**
1)I created a separate page for partner stores. Earlier it was missing so I designed one. 
2)Then I added the Partner Stores link to every page.
image

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
> 1)I created a separate page for partner stores. Earlier it was missing so I designed one.
> 2)Then I added the Partner Stores link to every page.
> image

Doesn't looks good.

Share website link.

**Comment by ushmita4** [comment]
> > 1)I created a separate page for partner stores. Earlier it was missing so I designed one.
> > 2)Then I added the Partner Stores link to every page.
> > image
> 
> Doesn't looks good.
> 
> Share website link.

Sir, which website link?

**Comment by QAZIMAAZARSHAD** [comment]
Host your website anywhere like repl.it, GitHub pages, etc., and share link so I can review your changes.

**Comment by QAZIMAAZARSHAD** [comment]
And always provide a descriptive title to your PR, not like this.

Also always mention your issue number in the PR description like this #49.

**Comment by ushmita4** [comment]
> And always provide a descriptive title to your PR, not like this.
> 
> Also always mention your issue number in the PR description like this #49.

https://ushmita4.github.io/Apni-Dukaan/

Sir, here I have provided the link?

Actually, sir, I am new to it so it is taking time for me to understand.

**Comment by QAZIMAAZARSHAD** [comment]
> > And always provide a descriptive title to your PR, not like this.
> > Also always mention your issue number in the PR description like this #49.
> 
> https://ushmita4.github.io/Apni-Dukaan/
> 
> Sir, here I have provided the link?
> 
> Actually, sir, I am new to it so it is taking time for me to understand.

Yaa fine.

There is always a first time.

**Comment by ushmita4** [comment]
Sir, how would I come to know that it has been merged?

**Comment by QAZIMAAZARSHAD** [comment]
Your changes have disturbed the navbar align it properly.

Partners page means Brands that are partners of Apni Dukaan means at Apni Dukaan users can find products of these brands like Lakme, Google, Lenskart, Reebok, Puma, etc.
So on the partner's page, you should have included logos of these brands.

From the changes you have made, it looks like you have created a feedback page.

So I am closing this PR.
Refer to some e-commerce websites to get an idea then start again.

**Comment by QAZIMAAZARSHAD** [comment]
> Sir, how would I come to know that it has been merged?

In place of closed it will be written merged.
And I will add DCP and level in your PR then consider your PR successfully merged.

**Pull request closed without merging**
