### PR TITLE
Added Cart page design with its functionality

### PR DESCRIPTION
**Pull request by K-jais**
Added Cart page design with its functionality which takes in the total amount of the products and can also take the number of products and according to that changes the total amount.

It resolves issue #24 

Its working video,

https://user-images.githubusercontent.com/75881393/125832321-f604e11f-b8b9-4ad2-a435-5c181718fd19.mp4

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

Add "My Cart" beside the category item in the navbar. And link this page.

**Comment by K-jais** [comment]
Added My cart beside the category item in the navbar. Please review it now

**Comment by QAZIMAAZARSHAD** [comment]
@K-jais don't add my cart inside category.
Add it beside the category section. Between search and category.

**Comment by K-jais** [comment]
Added My Cart between search and category. Please review it now.

**Comment by K-jais** [comment]
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Link?

**Comment by K-jais** [comment]
> Link?

Which link ?

**Comment by K-jais** [comment]
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Share your website link so I can review your changes

**Comment by K-jais** [comment]
https://k-jais.github.io/Apni-Dukaan/cart.html

**Comment by K-jais** [comment]
@QAZIMAAZARSHAD

**Pull request merged**
