### PR TITLE
linked about page, offers page, faq page  with home pages.

### PR DESCRIPTION
**Pull request by rohit306-bit**
#### Describe the changes you've made
here i made change in about.html and connect with it home page and i also made changes in offers.html and faq.html connect both of them with home page.

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)
apni-dukaan change

apni-dukaan1
apni-dukaan2

### CODE REVIEW

**Comment by Ashurajputt** [comment]
@rohit306-bit your repo is few commits behind.

Fetch upstream. 

Then I will merge it.

**Comment by QAZIMAAZARSHAD** [comment]
@rohit306-bit your repo is few commits behind.

Fetch upstream.

Then I will merge it.

**Comment by rohit306-bit** [comment]
> @rohit306-bit your repo is few commits behind.
> 
> Fetch upstream.
> 
> Then I will merge it.

i already mentioned it in code

**Comment by rohit306-bit** [comment]
In this repo i made a change in about.html page and linked the #180 .
i made change in offers.html page linked the #180 
i made change in faq.html page linked the #180

**Comment by QAZIMAAZARSHAD** [comment]
Not that,

Screenshot (195)


See your branch is 2 commits behind, You will see a fetch upstream button. Merge it.

**Comment by rohit306-bit** [comment]
i did't get your point , can you make it more clear plzz

**Comment by rohit306-bit** [comment]
got it ,done from my side now you merge my pull request.

**Pull request merged**
