### PR TITLE
Cares Page modification

### LINKED ISSUE #201: Improve the heading and edit content in Apni Dukaan Cares page

### PR DESCRIPTION
**Pull request by Akamourya18**
#### Changes made
Improved the heading of cares page and edited the content present over there.

### CODE REVIEW

**Comment by Akamourya18** [comment]
demo

**Comment by Akamourya18** [comment]
> @Akamourya18 the social media icons are missing in the footer. Make one more PR to correct it.

Ok. Working on it.

**Comment by Akamourya18** [comment]
> @Akamourya18 are you a part of DCP?

Yes

**Comment by QAZIMAAZARSHAD** [comment]
You have not filled the google form.

Fill it ASAP.

**Comment by QAZIMAAZARSHAD** [comment]
Ping me here when you are done.

**Pull request merged**
