### PR TITLE
Update pull_request_template.md

### LINKED ISSUE #66: update pull_request_template
In pull_request_template.md
Change
`Issue Number`

with 
`Fixes #(issue number) `
so that issue automatically get close on successful merge of PR

### PR DESCRIPTION
**Pull request by manasb15**
Fixes #66 

Replaced the Issue # format with fixes # in the issue number section of the document. 

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program names (DCP21)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@manasb15 you have only edited the comments.

You have to replace
 Issue Number -> Fixes #(issue number)

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD I wanted to ask how to do this:
"I have added my name in the contributors list at the end of README.md file."
which is mentioned in the checklist.

**Comment by QAZIMAAZARSHAD** [comment]
Fill the google form as well. Link in slack description.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I wanted to ask how to do this:
> "I have added my name in the contributors list at the end of README.md file."
> which is mentioned in the checklist.

No need it will be automatically fetched.

**Comment by QAZIMAAZARSHAD** [comment]
@manasb15 would you like to solve the same issue in my other projects.

You can open issue.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Yeah sure. No big deal. What other projects do you have except apna theatre? cause I have only joined these two on slack.

**Comment by QAZIMAAZARSHAD** [comment]
Voters registration portal and income tax calculator

**Pull request merged**
