### PR TITLE
Added separate section for Tv and Appliances(#7)

### LINKED ISSUE #7: Create a separate page of TV & Electric appliances

### PR DESCRIPTION
**Pull request by SanthoshPatkar**
Fixes #7 (issue number)
Describe the changes you've made
Added Tv and appliances section and linked the navigation bar on the index page. Necessary styles is added in the Style CSS file

Describe if there is any unusual behaviour of your code(Write NA if there isn't)
NA

Additional context (OPTIONAL)

Test plan (OPTIONAL)

Checklist
[✓ ] I have mentioned related issue number in PR description.
[ ✓] I have added screenshots and related demo links of my changes..
[✓ ] The title of my pull request is a short description of the requested changes.
[✓ ] My code follows the code style of this project.
[ ✓] My change requires a change to the documentation.
[✓ ] I have updated the documentation accordingly.
[  ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Do share website link every time you make PR.

**Comment by SanthoshPatkar** [comment]
@QAZIMAAZARSHAD https://cocky-engelbart-2e6615.netlify.app/

**Comment by QAZIMAAZARSHAD** [comment]
https://cocky-engelbart-2e6615.netlify.app/

Try reviewing yourself, everything is wrong,

Correct it.

**Comment by QAZIMAAZARSHAD** [comment]
Tv and appliances page is fine.

You have messed the idex page.


I suggest.
Clone the project again.
Add tv page.
Add images.
Link tv page to other pages.

Then make a new PR.

**Pull request closed without merging**
