### PR TITLE
Added furniture page

### LINKED ISSUE #11: Create a  furniture page

### PR DESCRIPTION
**Pull request by tjanhvi**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by tjanhvi** [comment]
https://tjanhvi.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
Still the same @tjanhvi.

The same mistakes, you have not made the suggested corrections.

But since the event is ending within an hour I am accepting this PR.

**Comment by QAZIMAAZARSHAD** [comment]
Fill the google form.

**Comment by tjanhvi** [comment]
> Fill the google form.
> 
> Fill it ASAP it might be closed soon.

where is the form

**Comment by QAZIMAAZARSHAD** [comment]
Are you part of DCP?

**Pull request merged**
