### PR TITLE
fix: update logo on webpages

### LINKED ISSUE #264: Update the logo on every web page
image

New Logo

Modify this image first by removing the bottom strip.

### PR DESCRIPTION
**Pull request by Anish-Sarawgi**
#### Deploy your changes to github page or netlify and mention deployment link:
https://apnii-dukaan.netlify.app/

#### Describe the changes you've made
Old logo is replaced with new logo in different pages of this site. Also the logo in the readme file is updated with the new logo.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Screenshot
Screenshot (43)
Similarly, in other pages the logo is replaced.

#### Test plan 
1. On bowser, run any html file in which the logo is present.
2. See the logo, the older one is replaced with the newer one.

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program names: Hacktoberfest

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Host website and share live link.

So, I can review your changes.

**Comment by Anish-Sarawgi** [comment]
> Host website and share live link.
> 
> So, I can review your changes.

Hey @QAZIMAAZARSHAD,
I have added the website link in the PR description. Now you can review my changes.

**Comment by QAZIMAAZARSHAD** [comment]
@update logo in the title bar.

image
Disable this hover effect. 

Try increasing the size of the logo in the navbar.

Update the logo in the readme as well.

**Comment by Anish-Sarawgi** [comment]
> @update logo in the title bar.
> 
> image Disable this hover effect.
> 
> Try increasing the size of the logo in the navbar.
> 
> Update the logo in the readme as well.

I have made the required changes. Hope now it will works

**Comment by QAZIMAAZARSHAD** [comment]
@Anish-Sarawgi logo is not updated in the title bar.
You have increased the size of the navbar, don't do it just increase the size of the logo, the navbar size should remain constant.

**Pull request merged**
