### PR TITLE
Make same nav bar and footer for all the webpages

### LINKED ISSUE #134: Correct navbar in all pages and link every page with each other
It will look decent . Some pages have  nave bar in dark blue color and too thick so i want to set it all in proper way..
Please assign me this issue.

### PR DESCRIPTION
**Pull request by tjanhvi**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist
- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

**Comment by tjanhvi** [comment]
> Share the website link so I can review your changes.

https://tjanhvi.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
Fetch upstream your branch is 1 commit behind.

Then I will merge.

**Comment by tjanhvi** [comment]
> Fetch upstream your branch is 1 commit behind.
> 
> Then I will merge.

I have made the changes and made an another pr for this.
#160

**Pull request closed without merging**
