### PR TITLE
Books page added

### PR DESCRIPTION
**Pull request by Abhishek-Sahoo**
**Fixes** #60 

**Description**:
1. Books link added to menu2.
2. Books page has been created.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

**Comment by Abhishek-Sahoo** [comment]
Website link: https://abhishek-sahoo.github.io/books.html

**Comment by QAZIMAAZARSHAD** [comment]
@Abhishek-Sahoo check again it is disoriented.

Your repo is not updated fetch upstream.
Somewhere background is white somewhere blue.
Navbar is also not proper.

**Comment by satyampgt4** [comment]
resolve conflict featch update

**Pull request closed without merging**
