### PR TITLE
Payment Gateway Integration #25

### LINKED ISSUE #25: Improve the payments page

### PR DESCRIPTION
**Pull request by Rishita11**
#### Fixes #(25)
 
       Fixes #25  
       Payment gateway Integration

I have added an HTML file to navigate the user to payment options. The various payment options available are
1) Card payment
2) Net Banking
3) Transfer later
4) UPI payment/QR
5) Wallet Payment

There is no unusual behavior in the code.

A screenshot of the final window is as follows:
Screenshot (256)

#### Checklist

- [x ] I have mentioned related issue numbers in the PR description.
- [x] I have added screenshots and related demo links of my changes.
- [ x] The title of my pull request is a short description of the requested changes.
- [x ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ x] Open Source Program name- DevIncept

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Rishita11 rename acme corp to Apni Dukaan.

Also share a deployment link so I can review your changes.

And is this demo or it is active?

**Comment by Rishita11** [comment]
Okay, I will rename it to Apni Dukaan. Here is the deployment link: https://rishita11.github.io/E-pay.github.io/ 
It is an active API that will send an email to the customer confirming the successful payment made by them.

**Comment by QAZIMAAZARSHAD** [comment]
Will there be an actual transaction?

**Comment by QAZIMAAZARSHAD** [comment]
Not that deploy your changes in this website then share link.

**Comment by Rishita11** [comment]
Okay, I will share that link in a while.

There will be transactions only when the person enters the OTP, otherwise, for a demo, he can skip that step and move ahead.

**Comment by QAZIMAAZARSHAD** [comment]
> Okay, I will share that link in a while.
> 
> There will be transactions only when the person enters the OTP, otherwise, for a demo, he can skip that step and move ahead.

That's too risky.

It's just a demo website. If anyone by chance makes a transaction then that will be an issue.

Use this account. I will have control over it.
qazimaazarshad.info@gmail.com
Password - a1234567

**Comment by Rishita11** [comment]
Okay, I will create another page for this that will be a dummy one and create a new PR.

**Comment by Rishita11** [comment]
I will create another page for this that will be a dummy one and create a new PR.

**Pull request closed without merging**
