### PR TITLE
made a simple card

### LINKED ISSUE #21: Improve or redesign product page

### PR DESCRIPTION
**Pull request by aditya687**
Fixes #21
 
made a responsive and simple product card

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@aditya687 share the website link so I can review your changes.

**Comment by aditya687** [comment]
Wait...

**Comment by aditya687** [comment]
https://github.com/aditya687/product-card

**Comment by QAZIMAAZARSHAD** [comment]
No not that.


Host your website on any platform like GitHub pages or netlify then share live link.

Like This -> https://qazimaazarshad.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
And looks like you have created separate product page.

Include it in the main website.
And don't create any separate folder like the product page.
Make the changes in the existing product.html.

**Comment by QAZIMAAZARSHAD** [comment]
This is the description of this issue

Whenever the user clicks on buy now on any product it should be redirected to this products page.
The product page must include pictures, product description, price, and add to cart and buy now button.
On clicking add to cart button it should be redirected to my cart page.
On clicking buy now it should be redirected to the payments page.

**Comment by aditya687** [comment]
Ok, I'll make it

**Pull request closed without merging**
