### PR TITLE
about us page

### PR DESCRIPTION
**Pull request by navyasrisangem**
Fixes #(52)
 
 Describe the changes you've made
redesigned about us page.

Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

Additional context (OPTIONAL)
ABOUTUS

 Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by navyasrisangem** [comment]
https://navyasrisangem.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
Always mention issue number like this #52.

**Comment by QAZIMAAZARSHAD** [comment]
Fill the google form in slack channel.

**Comment by QAZIMAAZARSHAD** [comment]
image


These are your changes.

**Comment by QAZIMAAZARSHAD** [comment]
Everything's wrong.

Correct It.
Make PR again.

**Comment by QAZIMAAZARSHAD** [comment]
@navyasrisangem are working on it to correct everything?

Or should I remove the labels?

**Comment by navyasrisangem** [comment]
Unassign me.

**Pull request merged**
