### PR TITLE
created login Page

### LINKED ISSUE #14: Create a login page

### PR DESCRIPTION
**Pull request by harshithatnbr**
#### Describe the changes you've made
I have created a login page . I have renamed login.html (which is signup page) to signup.html.

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
image

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program dcp 2021)

### CODE REVIEW

**Comment by harshithatnbr** [comment]
I am trying to deploy my website on repl.it . But when I run it I am getting original website . I have changed branch also. How to run the website with the changes I have made? Please let me know. Thankyou.

**Comment by QAZIMAAZARSHAD** [comment]
> I am trying to deploy my website on repl.it . But when I run it I am getting original website . I have changed branch also. How to run the website with the changes I have made? Please let me know. Thankyou.

Just import the GitHub repo on repl.it.

Or just go to settings on the repo, scroll down, click on GitHub pages you will get the link.

**Comment by harshithatnbr** [comment]
https://harshithatnbr.github.io/Apni-Dukaan/

link

**Comment by QAZIMAAZARSHAD** [comment]
Update navbar on the login page.

Remove the signup link from the navbar.

Add signup button within the login page.

**Comment by harshithatnbr** [comment]
Ok

**Comment by harshithatnbr** [comment]
I have updated as you said. Please review my PR. 
https://harshithatnbr.github.io/Apni-Dukaan/
Thankyou.

**Comment by QAZIMAAZARSHAD** [comment]
Remove signup link from every navbar.

**Pull request merged**
