### PR TITLE
Redesigned a fully responsive modern homepage

### LINKED ISSUE #84: I want to change the UI of the webpage.
The UI of the website is looking too old style and I want to give a modern look to the home page specially.

### PR DESCRIPTION
**Pull request by Subham-Satapathy**
#### Description:
I have redesigned a fully responsive home page of Apni Dukaan website using HTML, CSS, Bootstrap 5 . 

Chages:
I have redesigned the navbar with another logo which perfectly matches the color.
I have added some new features like card design of the product categories and also added some HINDI comments in the slider.
I have removed some designs which were not looking professional and added my design into it.
#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by satyampgt4 — APPROVED** [review]
Looking great!

**Comment by Subham-Satapathy** [comment]
Okay, should I make a new PR?

**Comment by QAZIMAAZARSHAD** [comment]
> Okay, should I make a new PR?

Make the necessary changes in this PR no need for a new one.

**Comment by Subham-Satapathy** [comment]
> > Okay, should I make a new PR?
> 
> Make the necessary changes in this PR no need for a new one.

Okay.

**Comment by satyampgt4** [comment]
> Actually deals,html was added yesterday and I had cloned the project 2 days back. So, should I make a new PR?

in that case fetch (pull) all the update from upstream

**Comment by Subham-Satapathy** [comment]
Check it now, I have updated the code.

> Looking great!
> 
> but I think link to "./deals.html" is missing

**Comment by Subham-Satapathy** [comment]
> Link to the deals page in navbar is still wrong

Yeah, done now.

**Pull request merged**
