### PR TITLE
Make individual CSS file for each html file

### LINKED ISSUE #132: Make individual CSS file for each html file.
Please assign me this issue

### PR DESCRIPTION
**Pull request by tjanhvi**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi share a deployment link so I can review your changes.

**Review by satyampgt4 — COMMENTED** [review]
every thing is fine 

just do one more thing if possible please move the CSS that is in style.css and written under  comment of an section to its respective CSS file like
this to baby and kids
image

this to about us
image

and this to FAQ
image

**Comment by tjanhvi** [comment]
> every thing is fine
> 
> just do one more thing if possible please move the CSS that is in style.css and written under comment of an section to its respective CSS file like
> this to baby and kids
> image
> 
> this to about us
> image
> 
> and this to FAQ
> image

okay

**Comment by tjanhvi** [comment]
https://tjanhvi.github.io/Apni-Dukaan/

**Review by satyampgt4 — APPROVED** [review]

**Comment by QAZIMAAZARSHAD** [comment]
image
image

image
image

image
image

image
image

image
image

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi and @satyampgt4 check and compare.

**Review by satyampgt4 — COMMENTED** [review]
may be because many pages are using class of other pages(like FAQ page use class of contact in style. css) it would not possible to change style.css
@tjanhvi please revert the change you have made in last commit rest is fine. sorry for inconvenience 
and also resolve the conflict

**Comment by tjanhvi** [comment]
> may be because many pages are using class of other pages(like FAQ page use class of contact in style. css) it would not possible to change style.css
> @tjanhvi please revert the change you have made in last commit rest is fine. sorry for inconvenience
> and also resolve the conflict

okay

**Pull request closed without merging**
