### PR TITLE
Books page added

### LINKED ISSUE #60: Create a page for Book
## Is your feature request related to a problem? Please describe.
Create a page for Books

### PR DESCRIPTION
**Pull request by Abhishek-Sahoo**
Fixes #60 

Description:

Books link added to category dropdown.
Books page has been created.

Review link: https://abhishek-sahoo.github.io/index.html

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Close old PR.

**Comment by QAZIMAAZARSHAD** [comment]
Update the navbar.

Remove the second navbar.

**Comment by Abhishek-Sahoo** [comment]
Old PR closed.
Navbar updated.
Second navbar and logo section removed.

**Comment by QAZIMAAZARSHAD** [comment]
image


Not reflected in the link you shared.

**Comment by Abhishek-Sahoo** [comment]
Now the link is updated. Check now.

**Pull request merged**
