### PR TITLE
Deals page

### LINKED ISSUE #6: Create a separate "Deals of the Day" page and remove deals section from home page

### PR DESCRIPTION
**Pull request by Swastik1710**
#### Describe the changes you've made
Added a new Deals of the Day and removed the Deals of the Day section from home page.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshot -

Screenshot 2021-07-12 142936

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) - DCP 2021

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Have you added one more row?

**Comment by Swastik1710** [comment]
> 
> 
> Have you added one more row?

I want to, but I'm not getting content for more.
Please suggest something.

**Comment by Swastik1710** [comment]
Okay, thanks
I'll do the additions and get back to you.

**Comment by Swastik1710** [comment]
Hey @QAZIMAAZARSHAD , I've added a new row as said. Here's a demo

ezgif com-gif-maker(4)

**Comment by Swastik1710** [comment]
Hey @QAZIMAAZARSHAD , I've added a new row as said.

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

**Comment by Swastik1710** [comment]
> Share the website link so I can review your changes.

Sorry I didn't get you!

**Comment by QAZIMAAZARSHAD** [comment]
Host your website on any platform and share link.

Like this https://qazimaazarshad.github.io/Apni-Dukaan/.

**Comment by Swastik1710** [comment]
Here you go
https://swastik1710.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
Correct navbar.

Add scroll to top button in deals page.

**Comment by Swastik1710** [comment]
Navbar was correct only but someone added the Partner Stores tab due to which it got messed up.
So now what to do?
Shall I change Deals of the Day to only Deals.

**Comment by QAZIMAAZARSHAD** [comment]
> Navbar was correct only but someone added the Partner Stores tab due to which it got messed up.
> So now what to do?
> Shall I change Deals of the Day to only Deals.

I think offers was better, change it to that.

**Comment by Swastik1710** [comment]
Done!
Please have a look @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Can't go to offers page from about us page.

**Comment by Swastik1710** [comment]
Please check now. 
Sorry for that.

**Pull request merged**
