### PR TITLE
Added error checking in contactUs & Link social media

### LINKED ISSUE #122: Add additional features to contact us page
## Is your feature request related to a problem? Please describe.
User can type symbol (+-$#@ etc.) in their name.
Email checking is not complete.

## Describe the solution you'd like
Adding regular expression with javascript to do checking.

## Additional context
+ Also link the social media button in contact us to corresponding social media website.

@QAZIMAAZARSHAD Can I work on this?

### PR DESCRIPTION
**Pull request by Sia0**
#### Describe the changes you've made
Added error checking on ContactUs page.
- Name, Email and Message input cannot be empty.
- Name input only accept alphabets and space (Digits and symbols are not allowed)
- Email input must be made up of _@_._ ( _ => refers to characters)
- If name or email input is invalid, submit button is disabled.

Added link to social media button and the email.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Additional context (OPTIONAL)
image
image
image
image

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by Sia0** [comment]
https://sia0.github.io/Apni-Dukaan/contactus.html
Here is the link for review.

**Comment by QAZIMAAZARSHAD** [comment]
@Sia0 fill the google form both your PR's.

Link in the slack channel.

**Comment by Sia0** [comment]
Sorry may I know what is slack channel? First time heard on this.

**Comment by QAZIMAAZARSHAD** [comment]
@Sia0 are you a part of DCP?

**Comment by Sia0** [comment]
uhmmm first time heard of this also. I think nope

**Comment by Sia0** [comment]
May I know what is it for?

**Comment by QAZIMAAZARSHAD** [comment]
DCP is an open-source contribution event and this project is part of that event.

If you want to know more click on the DCP logo in the readme file.
You can also participate if you wish.

**Comment by QAZIMAAZARSHAD** [comment]
Ooops looks like registrations have been closed.

**Comment by Sia0** [comment]
Ya I have just discovered that also. It's ok, btw thanks for your information.

**Comment by QAZIMAAZARSHAD** [comment]
https://lgmsoc.co/

LGMSoC is another open-source program my other projects are part of this program too.
You can participate in this if you want.

**Pull request merged**
