### PR TITLE
Title Bar

### PR DESCRIPTION
**Pull request by Swastik1710**
#### Describe the changes you've made
Changed Title bar text to Apni Dukaan and added favicon to the title bar as well.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) - DCP 2021

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Also, add this logo in the title bar.

**Comment by Swastik1710** [comment]
So you want me to add this logo instead of the previous one or you want both?

**Comment by satyampgt4** [comment]
> Done !

did you add link of favicon to header of page ..?

**Comment by Swastik1710** [comment]
No it's not at all needed.
If we name an .ico file as favicon it automatically shows up as Title bar logo.

**Review by satyampgt4 — APPROVED** [review]

**Comment by QAZIMAAZARSHAD** [comment]
@Swastik1710 fill this form https://docs.google.com/forms/d/e/1FAIpQLSeWRqZljejl0NnH8v4PqkjfTsWoQAbx_n0xR25PHaNiZnbnAw/viewform


Mention only those PR links which have DCP label.

**Comment by QAZIMAAZARSHAD** [comment]
@Swastik1710 
image


Favicon not visible correct it.

**Comment by Swastik1710** [comment]
It's working fine on my localhost but not on the website
Any idea why ?
Screenshot 2021-07-11 145709

**Comment by QAZIMAAZARSHAD** [comment]
> It's working fine on my localhost but not on the website
> Any idea why ?
> Screenshot 2021-07-11 145709

No idea.
Never used your technique.

Do it by writing code in HTML file.

**Pull request merged**
