### PR TITLE
Added  separate section for Tv and Appliances(#7)

### LINKED ISSUE #7: Create a separate page of TV & Electric appliances

### PR DESCRIPTION
**Pull request by SanthoshPatkar**
#### Describe the changes you've made
Added Tv and appliances section and linked the navigation bar on the index page. Necessary styles is added in the Style CSS file

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshot (117)
Screenshot (118)
Screenshot (119)
Screenshot (120)
Screenshot (121)

#### Checklist

- [✓ ] I have mentioned related issue number in PR description.
- [ ✓] I have added screenshots and related demo links of my changes..
- [✓ ] The title of my pull request is a short description of the requested changes.
- [✓ ] My code follows the code style of this project.
- [ ✓] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@SanthoshPatkar update the footer and navbar.

It should be similar to the new updated navbar as in index page.

Also resolve conflicts.

**Comment by SanthoshPatkar** [comment]
@QAZIMAAZARSHAD  I have resolved the conflicts.

**Comment by QAZIMAAZARSHAD** [comment]
Host your website somewhere like GitHub pages, netify, repl.it then share website link so I can review your changes.

**Comment by SanthoshPatkar** [comment]
@QAZIMAAZARSHAD https://cocky-engelbart-2e6615.netlify.app

**Comment by QAZIMAAZARSHAD** [comment]
First,
Fetch upstream update your repo.

Don't disturb any other page.

image
Remove this navbar.
And there is only one image in the slider, update the images and add images related to electronics.

All the cards should be of the same size.

**Comment by QAZIMAAZARSHAD** [comment]
Correct everything then make a new PR.

**Pull request closed without merging**
