### PR TITLE
FAQ page changes

### PR DESCRIPTION
**Pull request by Swastik1710**
#### Describe the changes you've made
Added a new faq page with some common questions keeping in mind the website theme and the responsiveness.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Demo :

125086178-fd33d880-e0e8-11eb-81e5-7c286d7a8849

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) - DevIncept Contribution Program

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Swastik1710 you forgot to link this page with other pages.

**Comment by Swastik1710** [comment]
Oh okay. I'll make the necessary changes and get back to you.
BTW, may I know that on what grounds has this been labelled as Level1 ?

**Comment by QAZIMAAZARSHAD** [comment]
> Oh okay. I'll make the necessary changes and get back to you.
> BTW, may I know that on what grounds has this been labelled as Level1 ?

The number of lines of code.
Efforts put.
Quality.

Level = 10

**Comment by Swastik1710** [comment]
Thanks for the clarification.

**Comment by Swastik1710** [comment]
Hey , I've made the suggested changes.
Please have a look.

**Comment by QAZIMAAZARSHAD** [comment]
@Swastik1710 have a look.

https://qazimaazarshad.github.io/Apni-Dukaan/faq.html

**Comment by QAZIMAAZARSHAD** [comment]
Correct it.

Also, edit Lorem Lipsum.
Write meaningful things.

**Comment by Swastik1710** [comment]
I didn't get you
What do I need to correct?

**Comment by Swastik1710** [comment]
Amd for the lorem ipsum part, I don't know your policies regarding all those questions so I didn't change them.

**Comment by QAZIMAAZARSHAD** [comment]
A few minutes earlier your page was completely disoriented that's why I said.

I think GitHub pages take time to update all the changes.

**Comment by Swastik1710** [comment]
> 
> 
> A few minutes earlier your page was completely disoriented that's why I said.
> 
> I think GitHub pages take time to update all the changes.

It's looking fine as of now.
FireShot Capture 053 - ApniDukaan com - qazimaazarshad github io

**Comment by QAZIMAAZARSHAD** [comment]
> And for the lorem ipsum part, I don't know your policies regarding all those questions so I didn't change them.

Just refer to some websites and write answers, we don't have any policies because this is not an actual company this is just a demo website. But still, Lorem Lipsum ruins everything so enter some meaningful text.

**Comment by Swastik1710** [comment]
Okay no worries.
So shall I create a new PR or how I am supposed to do it.

**Comment by QAZIMAAZARSHAD** [comment]
> > A few minutes earlier your page was completely disoriented that's why I said.
> > I think GitHub pages take time to update all the changes.
> 
> It's looking fine as of now.
> FireShot Capture 053 - ApniDukaan com - qazimaazarshad github io

Yaa now its fine. Previously It was looking like it has no CSS.

**Comment by Swastik1710** [comment]
Hey @QAZIMAAZARSHAD  , I've raised a new PR #62 
Please have a look.

**Comment by QAZIMAAZARSHAD** [comment]
Fill this form https://docs.google.com/forms/d/e/1FAIpQLSeWRqZljejl0NnH8v4PqkjfTsWoQAbx_n0xR25PHaNiZnbnAw/viewform

**Pull request merged**
