### PR TITLE
added booking&order page

### PR DESCRIPTION
**Pull request by aishwaryas15**
Added the "Booking/Purchase" page which redirects to an order page further.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

Also, you have not linked your page to the website.
Add books section in categories navbar of all pages.

**Comment by QAZIMAAZARSHAD** [comment]
@aishwaryas15 for which issue you have made this PR mention the issue number.

**Comment by aishwaryas15** [comment]
ya I'll link them

**Comment by aishwaryas15** [comment]
#34

**Comment by QAZIMAAZARSHAD** [comment]
@aishwaryas15 share the website link so I can review your PR.

**Comment by QAZIMAAZARSHAD** [comment]
@aishwaryas15 share a link to your website so we can proceed further.

**Pull request closed without merging**
