### PR TITLE
Added Stationery Page

### LINKED ISSUE #76: Create a page for stationary
I am a contributor from devincept. I would like to create a page for stationary in the project. Please assign me an issue for the same.

### PR DESCRIPTION
**Pull request by devesh-2002**
Fixes #76 
I have created a page for stationery and did some changes which were been told.
image

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

Looks like you have done many unnecessary changes in the index page.

**Comment by devesh-2002** [comment]
https://devesh-2002.github.io/Apni-Dukaan/

**Comment by QAZIMAAZARSHAD** [comment]
Don't forget to fill the google form. Link in the slack channel.

**Comment by devesh-2002** [comment]
Thanks a lot!

**Pull request merged**
