### PR TITLE
Update Stationery Page

### LINKED ISSUE #131: Redesign Stationery Page
## Is your feature request related to a problem? Please describe.
The design of the stationery page is not consistent with the home page.
The view all brands button is not functioning.

## Describe the solution you'd like
Redesign the stationery page to meet the styling of home page.
Add JavaScript to make the view all button function 

## Additional context
Could you assign this issue to me?

### PR DESCRIPTION
**Pull request by gassa097**
#### Describe the changes you've made
Modified styling of the stationery page
Update JavaScript in stationery page to make view all button functional
Make new directory for stationery images

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Link: https://gassa097.github.io/Apni-Dukaan/stationery.html
New Stationery Page
Show more button

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@gassa097 remove the second navbar.

Also share the website link so I can review your chages.

**Comment by gassa097** [comment]
The second navbar is removed.
Website link: https://gassa097.github.io/Apni-Dukaan/stationery.html

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (76)
 
Remove this part and add a slider.
Also, rename view all brands to "View More".

**Comment by gassa097** [comment]
Slider added.
View More button renamed.

**Comment by QAZIMAAZARSHAD** [comment]
Are you part of DCP?

**Comment by gassa097** [comment]
I am not part of DCP.

**Pull request merged**
