### PR TITLE
Book-Page

### PR DESCRIPTION
**Pull request by 2024-SANDHYA**
Solves the issue #165 

1. Changed the look of the section.
2. Added Cards.
3. Hover Effects
4. Worked on detailing
5. Added books of different categories.

@QAZIMAAZARSHAD Enhancement can be checked here : https://2024-sandhya.github.io/Apni-Dukaan/

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
image


Is this like this?

**Comment by 2024-SANDHYA** [comment]
> 
> 
> image
> 
> Is this like this?

No it's not like this. I'll fix this

**Comment by 2024-SANDHYA** [comment]
> 
> 
> image
> 
> Is this like this?

@QAZIMAAZARSHAD  Please view it again. Fixed the issues !!

**Comment by QAZIMAAZARSHAD** [comment]
Fetch upstream your repo is few commits behind.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Fetch upstream your repo is few commits behind.

Done !! @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> > Fetch upstream your repo is few commits behind.
> 
> Done !! @QAZIMAAZARSHAD

Nope.

Still 4 commits behind.

**Comment by QAZIMAAZARSHAD** [comment]
image

**Comment by 2024-SANDHYA** [comment]
> 
> 
> > > Fetch upstream your repo is few commits behind.
> > 
> > 
> > Done !! @QAZIMAAZARSHAD
> 
> Nope.
> 
> Still 4 commits behind.
Screenshot 2021-07-28 at 13-22-21 2024-SANDHYA Apni-Dukaan An E-commerce site to buy products of need

It's even

**Comment by QAZIMAAZARSHAD** [comment]
Yes that's even but you made PR with the DCP21 branch.

Change branch then fetch upstream.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Yes that's even but you made PR with the DCP21 branch.
> 
> Change branch then fetch upstream.

DONE !!

**Comment by QAZIMAAZARSHAD** [comment]
@2024-SANDHYA the font in your footer is different from other pages.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> @2024-SANDHYA the font in your footer is different from other pages.

Fixed! @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> > @2024-SANDHYA the font in your footer is different from other pages.
> 
> Fixed! @QAZIMAAZARSHAD

Nope push changes.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> > > @2024-SANDHYA the font in your footer is different from other pages.
> > 
> > 
> > Fixed! @QAZIMAAZARSHAD
> 
> Nope push changes.

@QAZIMAAZARSHAD  DONE !

**Pull request merged**
